// src/data.js
export const users = [
  {
    email: "joseph@replicaide.com",
    password: "12345678",
    username: "Joseph Bouhlel",
  },
  {
    email: "amin@replicaide.com",
    password: "12345678",
    username: "Amin Abdi",
  },
];
export const Calls = [
  {
    clientInfo: {
      firstName: "Geoff",
      lastName: "Smith",
      email: "geoffsmith@gmail.com",
      phone: "702-55-1212",
    },
    propertyInfo: {
      address: "1116 Ocean Drive",
      city: "Miami Beach",
      state: "Florida",
      zip: "33139",
      surface: "5000 sq/f",
      rooms: 5,
      bathrooms: 6,
    },
    messages: [
      { isAgent: true, text: "Good morning, how can I assist you?" },
      { isAgent: false, text: "I’d like to know more about the property." },
    ],
    audio: "./demo.mp3",
    date: "2023-11-16",
    notes: "Client is very interested in oceanfront properties.",
    image: "https://thumbor.forbes.com/thumbor/fit-in/900x510/https://www.forbes.com/home-improvement/wp-content/uploads/2022/07/Paris_Exterior_4-Edit-e1714649473120.png",
  },
  {
    clientInfo: {
      firstName: "Anna",
      lastName: "Johnson",
      email: "anna.johnson@gmail.com",
      phone: "312-45-6789",
    },
    propertyInfo: {
      address: "14 Sunset Boulevard",
      city: "Los Angeles",
      state: "California",
      zip: "90028",
      surface: "4000 sq/f",
      rooms: 4,
      bathrooms: 5,
    },
    messages: [
      { isAgent: true, text: "Hello, Anna. How can I help today?" },
      { isAgent: false, text: "Can you send me details on the listing?" },
    ],
    audio: "./demo.mp3",
    date: "2023-11-15",
    notes: "Requested virtual tour information.",
    image: "https://www.bhg.com/thmb/H9VV9JNnKl-H1faFXnPlQfNprYw=/1799x0/filters:no_upscale():strip_icc()/white-modern-house-curved-patio-archway-c0a4a3b3-aa51b24d14d0464ea15d36e05aa85ac9.jpg",
  },
  {
    clientInfo: {
      firstName: "Michael",
      lastName: "Brown",
      email: "michael.brown@gmail.com",
      phone: "415-67-8901",
    },
    propertyInfo: {
      address: "88 Bay Street",
      city: "San Francisco",
      state: "California",
      zip: "94133",
      surface: "3000 sq/f",
      rooms: 3,
      bathrooms: 4,
    },
    messages: [
      { isAgent: true, text: "Hi Michael, what can I do for you?" },
      { isAgent: false, text: "What are the monthly fees for this property?" },
    ],
    audio: "./demo.mp3",
    date: "2023-11-14",
    notes: "Client wants cost breakdown for condos.",
    image: "https://media.onthemarket.com/properties/16128318/1518230897/image-2-480x320.jpg",
  },
  {
    clientInfo: {
      firstName: "Jessica",
      lastName: "Taylor",
      email: "jessica.taylor@gmail.com",
      phone: "646-32-1098",
    },
    propertyInfo: {
      address: "20 Central Park West",
      city: "New York",
      state: "New York",
      zip: "10023",
      surface: "2500 sq/f",
      rooms: 2,
      bathrooms: 3,
    },
    messages: [
      { isAgent: true, text: "Hi Jessica, how can I assist you today?" },
      { isAgent: false, text: "Can you provide the HOA information?" },
    ],
    audio: "./demo.mp3",
    date: "2023-11-13",
    notes: "Awaiting HOA documentation from the owner.",
    image: "https://town-n-country-living.com/wp-content/uploads/2023/06/craftsman-exterior.jpg",
  },
  {
    clientInfo: {
      firstName: "Robert",
      lastName: "Wilson",
      email: "robert.wilson@gmail.com",
      phone: "702-89-2345",
    },
    propertyInfo: {
      address: "77 Strip Avenue",
      city: "Las Vegas",
      state: "Nevada",
      zip: "89109",
      surface: "3500 sq/f",
      rooms: 4,
      bathrooms: 5,
    },
    messages: [
      { isAgent: true, text: "Good afternoon, Robert!" },
      { isAgent: false, text: "How flexible is the seller on price?" },
    ],
    audio: "./demo.mp3",
    date: "2023-11-12",
    notes: "Negotiating terms with the seller.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjtH2Sklx2mXrE7-njf7bqy_mvW-2W0AXzaQ&s",
  },
  {
    clientInfo: {
      firstName: "Emily",
      lastName: "Clark",
      email: "emily.clark@gmail.com",
      phone: "503-12-3456",
    },
    propertyInfo: {
      address: "555 Rose Garden Lane",
      city: "Portland",
      state: "Oregon",
      zip: "97210",
      surface: "3200 sq/f",
      rooms: 3,
      bathrooms: 4,
    },
    messages: [
      { isAgent: true, text: "Hi Emily, what’s on your mind today?" },
      { isAgent: false, text: "Can I schedule a walkthrough?" },
    ],
    audio: "./demo.mp3",
    date: "2023-11-11",
    notes: "Scheduled walkthrough for next week.",
    image: "https://www.properties.market/in/blog/wp-content/uploads/2024/01/5-Most-Lavish-And-Expensive-Celebrity-Owned-Houses-In-Hyderabad-1200x675.png",
  },
  {
    clientInfo: {
      firstName: "David",
      lastName: "Martinez",
      email: "david.martinez@gmail.com",
      phone: "818-56-7890",
    },
    propertyInfo: {
      address: "101 Hollywood Drive",
      city: "Hollywood",
      state: "California",
      zip: "90038",
      surface: "4500 sq/f",
      rooms: 5,
      bathrooms: 6,
    },
    messages: [
      { isAgent: true, text: "Hello David, how’s it going?" },
      { isAgent: false, text: "Can you explain the zoning regulations?" },
    ],
    audio: "./demo.mp3",
    date: "2023-11-10",
    notes: "Follow up with city zoning department.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPNXkUAfzN1zIis7vf0rS9P9bizKEhzSOrMv-RdA30KIBIly9i6HMXGkit3YgjR734f6k&usqp=CAU",
  },
];
